### PR TITLE
Update MSR-1.yaml

### PR DESCRIPTION
**Pull request by neilmartin83**
Change framework from arduino to esp-idf per ESPHome recommendations for this board type

Change light platform from NeoPixelBus to ESP32 RMT LED Strip to make RGB LED compatible with esp-idf.

Been running mine like this for a few days with no issues - all sensors, web server, radar, buzzer and LED working perfectly.

Checks:
- [ ] Documentation Updated
- [ ] Build Number Incremented In MSR-1.yaml
- [ ] Build Number Incremented In manifest.json
- [ ] firmware-factory.bin Updated

### CODE REVIEW

**Comment by neilmartin83** [comment]
Just to add, although not included in this PR - I can confirm the following is working:

- added `logger:` with no other options so I can stream logs from ESPHome easily.
- Enabled bluetooth proxy which I use with the Private BLE Home Assistant integration to track my family's iPhones and Apple Watches - works great and detects us coming/going approx 15m away from the house. My config is:
```
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light

bluetooth_proxy:
  active: true
```

Both of the above don't make the image too large and I can flash OTA just fine - it would be great to add this functionality into the product itself as the bluetooth proxy really gives it more value IMO. Happy to submit a PR for it.

The following changes are for better security and might be worth a KB - as they affect functionality, can be fiddly to implement and are more down to personal preference:

- Removed the web server platform on my own config as I didn't want an open unencrypted web server on my network.
```
web_server: !remove
```
- Changed the default OTA password using the lambda from https://esphome.io/components/ota.html#changing-an-existing-password
- Also added API encryption to my config so traffic between the sensor and Home Assistant is encrypted (stored the key in my `secrets.yaml` file under `apollo-msr-1-38c3bc_api_encryption_key`):
```
api:
  encryption:
    key: !secret apollo-msr-1-38c3bc_api_encryption_key
```

I can give more details on the steps involved for the API encryption if it's helpful - please gimme a shout.

**Comment by TrevorSchirmer** [comment]
Neil, thanks for the contribution! We switched to the ESP IDF on MSR-2 and MTR-1 but hadn't updated MSR-1 just because I was worried about the update process through ESPHome. I'll give it a go on my sensor this week though.

Thanks for the tips on the others. With the web server, encryption, and OTA password we've left that up to the user to add/remove/edit through the ESPHome addon if they'd like. 

Bluetooth proxy had a lot of warnings on the ESPHome site and we were worried about stability, so we opted to make a wiki article showing how users can add it if they'd want. I've not heard of any stability issues though from people, just when ESPHome had a weird bug where the image size was really large.

I'll check the update process this week!

Thanks!

**Comment by neilmartin83** [comment]
Thanks Trevor,

No issues with image size and OTA updates here - I've done quite a few with/without various components enabled.

Fingers crossed your testing goes well!

**Comment by TrevorSchirmer** [comment]
@neilmartin83 We did some more research and switching to ESPIDF would break OTA updates for existing users. They would have to flash once with the sensor plugged in before the OTA would continue to work. It has to do with the partitions in the ESP memory needing to be rebuild when switching from arduino to ESP.

So for now until that is added to ESPHome as something that can be done OTA we are going to stick with arduino. 

I greatly appreciate the contribution though, our future sensors have been being built on the ESPidf

**Pull request closed without merging**
